--
-- Undead racial Underwater Breathing (5227): infinite underwater breathing.
-- SPELL_AURA_MOD_WATER_BREATHING +233% -> SPELL_AURA_WATER_BREATHING (Player::getMaxTimer disables the
-- breath timer while it is on). spell_dbc overrides the Spell.dbc row. Generated by
-- client-patches/racial-spells/build_undead_breathing.py (client: Data\patch-Z.mpq) - edit the
-- builder, not this file.
--
DELETE FROM `spell_dbc` WHERE `ID` = 5227;
INSERT INTO `spell_dbc` VALUES (5227, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 6, 0, 0, 1, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 82, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 545, 0, 0, 'Underwater Breathing', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'Racial Passive', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, 'You can breathe underwater indefinitely.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 1.0, 1.0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0);
